"""Initial migration with updated all models

Revision ID: d9256aa6c0d4
Revises: 
Create Date: 2025-10-15 15:54:19.417112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9256aa6c0d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('links', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=64), nullable=False),
    sa.Column('course_description', sa.String(length=256), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('teacher', sa.String(length=64), nullable=True),
    sa.Column('course_duration', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('section_order', sa.Integer(), nullable=True),
    sa.Column('section_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_sections_course_id'), ['course_id'], unique=False)

    op.create_table('tuition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('tuition_amount', sa.Float(), nullable=False),
    sa.Column('rate_per_lesson', sa.Float(), nullable=False),
    sa.Column('rate_per_hour', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('lesson_quantity', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(end_time IS NULL) OR (end_time >= start_time)', name='ck_end_ge_start'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['course_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.create_index('idx_clsched_teacher_course', ['teacher_id', 'course_id'], unique=False)
        batch_op.create_index('idx_clsched_teacher_section', ['teacher_id', 'section_id'], unique=False)
        batch_op.create_index('idx_clsched_teacher_start_time', ['teacher_id', 'start_time'], unique=False)
        batch_op.create_index('idx_clsched_teacher_student', ['teacher_id', 'student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_section_id'), ['section_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_schedules_teacher_id'), ['teacher_id'], unique=False)

    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(rating IS NULL) OR (rating BETWEEN 1 AND 5)', name='ck_feedback_rating_range'),
    sa.ForeignKeyConstraint(['schedule_id'], ['class_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index('idx_feedback_student_created', ['student_id', 'created_at'], unique=False)
        batch_op.create_index('idx_feedback_teacher_created', ['teacher_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedbacks_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_student_id'))
        batch_op.drop_index(batch_op.f('ix_feedbacks_schedule_id'))
        batch_op.drop_index('idx_feedback_teacher_created')
        batch_op.drop_index('idx_feedback_student_created')

    op.drop_table('feedbacks')
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_schedules_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_class_schedules_student_id'))
        batch_op.drop_index(batch_op.f('ix_class_schedules_section_id'))
        batch_op.drop_index(batch_op.f('ix_class_schedules_course_id'))
        batch_op.drop_index('idx_clsched_teacher_student')
        batch_op.drop_index('idx_clsched_teacher_start_time')
        batch_op.drop_index('idx_clsched_teacher_section')
        batch_op.drop_index('idx_clsched_teacher_course')

    op.drop_table('class_schedules')
    op.drop_table('tuition')
    with op.batch_alter_table('course_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_sections_course_id'))

    op.drop_table('course_sections')
    op.drop_table('students')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_teacher_id'))

    op.drop_table('courses')
    op.drop_table('users')
    # ### end Alembic commands ###
